### ISSUE TITLE
changeSlide option fired twice on last slide

### ISSUE THREAD

**Issue by stefancova** [iosscripts/iosslider#105]
Hi, 
The changeSlide  is still firing twice in stead of once but only with the last slide.
Do you know how to fix this.

Thanks

**Comment by iosscripts** [comment]
That probably shouldn't be happening. Do you have a link to a demo/test case I could look at?

**Comment by ColColonCleaner** [comment]
Yes it was happening for me as well.

I'll explain in a little more detail. It only happens when the slider is at the right-most slide, so the last slide visible in the right hand side, is the last slide in the slider. Once the user begins to pull the slider past the last slide, onslidechange is fired and the slide index is incremented. So far i have only tested using my slider which has multiple slides on screen, so im not sure about your single slide case (which im assuming is your usual test case).

The error is visually not noticeable, it only came to my attention because i had position marking dots that were being pushed off the end when this happened.

EX: o = visible, x=not, 3 slides on screen
Dots: XXOOO 
so last slides are visible.

action: begin to drag slider past the end (pull it more to the left)
Dots result: XXXOO

it happens the instant slider is pulled past it's ending point, not when the slides pass their halfway point like the other times onchange is fired.

**Comment by stefancova** [comment]
My test case is the 7-Centered-Slides demo, I log the "onSlideChange" statement and it's fired two times at the last slide.

It's happen in autoslide, prev, next, and swipe mode

Here is a snaphot of firefox console with 3 slides :
http://www.flickr.com/photos/paradire/7999798156/in/photostream

**Comment by ColColonCleaner** [comment]
Also if ^ logged the currentSlideNumber param in the args array, it would be incremented one more time than it should be.

**Comment by iosscripts** [comment]
Fantastic, I see it. I will try and get a fix out for ya.

**Comment by stefancova** [comment]
Thanks !

**Comment by iosscripts** [comment]
This has been resolved in v1.1.2.

**Comment by stefancova** [comment]
Hello Mark, 

I have an absolute DIV (named "#slider-cache") positionned  hover the "iosslider" because of the design.
I already bind the "navNextSelector to #nav-next" and the "navPrevSelector to #nav-prev" in the #slider-cache and it's work well

But I dont know to bind the 'swipe' effect to the #nav-current.
Do you know how can i do this ?

Here's a example of my code and an image to help you to understand my case

Thanks a lot
Stefan

---

 De : Marc Whitbread notifications@github.com
À : iosscripts/iosSlider iosSlider@noreply.github.com 
Cc : stefan cova stecova@yahoo.fr 
Envoyé le : Mardi 2 octobre 2012 16h31
Objet : Re: [iosSlider] changeSlide option fired twice on last slide (#105)

This has been resolved in v1.1.2.
—
Reply to this email directly or view it on GitHub.
--------- part of HTML --------

<div id="slider-cache">
    <div id="nav-prev"></div>
    <div id="nav-current"></div>
    <div id="nav-next"></div>
</div>

<div class ="ios-container-outer">
    <div class ="ios-container">
        <div class ="ios-slider-container">
            <div class="ios-slider">
                <div class="slider">
                    <div class="slide">...</div>
                    <div class="slide">...</div>
                    <div class="slide">...</div>
                </div>
            </div>
        </div>
    </div>
</div>

--------- part of CSS --------
#slider-cache{
    position : absolute;
    z-index  : 20;
}

.ios-container-outer{
    position : absolute;
    z-index  : 10;
}

**Comment by stefancova** [comment]
Mark, 
Forget this email, i have found the solution with the CSS attribute 'pointer-events', 'none'

Thanks

---

 De : stefan cova stecova@yahoo.fr
À : iosscripts/iosSlider reply@reply.github.com 
Envoyé le : Jeudi 11 octobre 2012 11h46
Objet : Re: [iosSlider] changeSlide option fired twice on last slide (#105)

Hello Mark, 

I have an absolute DIV (named "#slider-cache") positionned  hover the "iosslider" because of the design.
I already bind the "navNextSelector to #nav-next" and the "navPrevSelector to #nav-prev" in the #slider-cache and it's work well

But I dont know to bind the 'swipe' effect to the #nav-current.
Do you know how can i do this ?

Here's a example of my code and an image to help you to understand my case

Thanks a lot
Stefan

---

 De : Marc Whitbread notifications@github.com
À : iosscripts/iosSlider iosSlider@noreply.github.com 
Cc : stefan cova stecova@yahoo.fr 
Envoyé le : Mardi 2 octobre 2012 16h31
Objet : Re: [iosSlider] changeSlide option fired twice on last slide (#105)

This has been resolved in v1.1.2.
