### ISSUE TITLE
video elements not draggable on iOS

### ISSUE THREAD

**Issue by ghost** [iosscripts/iosslider#122]
Hi,

I would like to implement the slider responsive and insert clickable content. The problem is that when I add a video in the slider for example, it is not draggable on mobile from the surface of the video. 

Do you have a solution for this problem?

**Comment by iosscripts** [comment]
What does your video embed code HTML look like? There are limitations when using iFrames to embed content within slides. ie. Drag events on the slider will not work when touching iFrame elements.

**Comment by ghost** [comment]
A code HTML look like this :

<img src="http://dev.cotecine.fr/~gauthier/tmp/screen01.jpg" />

What type of embed content can I use within slides ? (which remain draggable)

**Comment by iosscripts** [comment]
So just to confirm, you are able to drag on desktop but not mobile correct?

**Comment by ghost** [comment]
Yes but on desktop I disabled the option because the video starts after drag on Firefox.

**Comment by iosscripts** [comment]
video seems to work on iOS without the controls attribute set. The downside is you will have to make your own (which isn't super hard to do :S). When controls is set, all of the events (touch, click, etc.) are absorbed by the video element. So that's why it disables the slider. 

Ref: http://stackoverflow.com/questions/3469781/ipad-touch-events-on-video-tag

Some further research is telling me that this might be a iOS browser bug because every other browser handles video events properly.
