### ISSUE TITLE
Option to change touch sensitivity

### ISSUE THREAD

**Issue by philippkuehn** [iosscripts/iosslider#233]
I don't see an option for this. If I move very slowly my finger the slider doesn't move. It would be nice to adjust this "minimum start speed" for dragging on touch devices.

**Comment by marcwhitbread** [comment]
The lack of customization is intentional. Playing with these values cause headaches for end users sometimes, producing undesirable usability... and then they complain to me lol. For example, if no minimum sensitivity exists and the user swipes vertically over the slider, the slider will move horizontally inadvertently.

Anyway, I have lowered the minimum horizontal velocity threshold to 0 in v1.2.2 to see how the general public responds to the change. The vertical lock velocity will remain at 5px. That means that the slider will always respond to touch horizontally but will not lock vertical movement until a horizontal velocity of 5px is reached.

Let me know if you find this change an overall improvement to the usability of the slider.

**Comment by philippkuehn** [comment]
Ok, I understand the problem. And yeah, thanks. It's much better for me now!
