### ISSUE TITLE
Load and Unloading DIV elements when visible

### ISSUE THREAD

**Issue by bricolage8067** [iosscripts/iosslider#237]
I'm using the slider to display external content through an iFrame such as Adobe Edge animations and YouTube clips.

Can I trigger the content within the slide to load only when that specific slide is visible and then unload when swiping further? 

Any help is appreciated.

**Comment by marcwhitbread** [comment]
iFrames don't work well in general, so they will be a huge pain regardless of what you are trying to do.

Use could the onSlideComplete callback function to load HTML content into your slides. The only problem might be that if you are using iframes/video within the slides, the touch functionality will break due to browser limitations.
