### ISSUE TITLE
Problems with the two sliders on the same page

### ISSUE THREAD

**Issue by al5dy** [iosscripts/iosslider#249]
...

**Comment by marcwhitbread** [comment]
I think I know what the issue is... but I'm not 100% sure without seeing a demo of your issue. Can you provide a link to a demo with the issue if this doesn't work?

Without knowing what the structure of your HTML is, here is an example of setting up your buttons based on demo 4 if you had multiple sliders on the page. Here's what I propose:

``` js
$('.iosSlider').each(function() {

    $(this).iosSlider({
        /* other parameters */
        navNextSelector: $(this).find('.nextButton'),
        navPrevSelector: $(this).find('.prevButton')
    });

});
```

Let me know if that works.

**Comment by marcwhitbread** [comment]
Where are the non-working back/forward buttons? I cannot find or understand the problem you are talking about. I'm having trouble with your English, sorry.

**Comment by marcwhitbread** [comment]
No problem. I'm glad that fixed it! :+1:
