### ISSUE TITLE
embed youtube in slide

### ISSUE THREAD

**Issue by mmeester** [iosscripts/iosslider#252]
I've tried to embed a youtube video in a slide, this is al working in safari and chrome only firefox seems to have difficulties with it, the video is shown but unable to start by clicking the play button.

I've tried the iframe embed and the "old" embed code but both aren't working, I also tried the embed outside the video and that seemed to work without any problems.

**Comment by marcwhitbread** [comment]
In most cases, embedding video in slides does not work because in some browsers video elements absorb all touch/click events, preventing the slider from functioning. Can you give me your HTML so I can be sure?

**Comment by mmeester** [comment]
you can view it on staging here: http://staging.jaarverslag.growingdev.nl/

**Comment by marcwhitbread** [comment]
Thanks for the link. Take a look at the unselectableSelector option. Add a class to your video element and the slider will not override touch/click events in that element. Like so:

HTML

``` html
<iframe class = 'unselectable' />
```

JS

``` js
$(element).iosSlider({
    /* your other parameters */
    unselectableSelector: '.unselectable'
});
```

Let me know if that gets functionality back.

**Comment by mmeester** [comment]
unfortunatly this doesn't solve it, it's on staging again to view.... any other options?

**Comment by marcwhitbread** [comment]
Something wierd is going on with the clickable hit-box of the iframe. I added a youtube iframe embed to one of the demos in the download package and I'm getting the same thing. 

In my example you can mouse over the clickable hit-box of the video but it's moved up 50 pixels. You can't see the hit-box but the youtube player hover/click events respond when clicking 50 pixels above where they appear. This seems like a browser bug to me because I know my script doesn't control the location of any events applied to children.

So unfortunately, I have to go back to what I said above about embedded videos being unsupported due to browser limitations. What I would propose if you still want to use iosslider is to use the video thumbnail image in stead and have that open to a lightbox with the video or load it in asynchronously when clicking the image.
