### ISSUE TITLE
Does not work on Chrome 28 on Android

### ISSUE THREAD

**Issue by digitaljohn** [iosscripts/iosslider#297]
You cannot touch and swipe left and right. It seems to latch on... but only moves a few pixels.

To me it looks like an issue with the main page scroll bars activating and throowing out any touch interaction.

Just try and interact with your main homepage demo to replicate:
https://iosscripts.com/iosslider/

**Comment by marcwhitbread** [comment]
Have you tried modifying the slideStartVelocityThreshold or horizontalSlideLockThreshold values in your setup? Does lowering those values have any effect?

**Comment by digitaljohn** [comment]
Setting `horizontalSlideLockThreshold` to `3` feels perfect.

Specifically tested on Chrome 28, Android, Google Nexus 7.

Is there a reason why `3` could not be default? I am curious if setting `3` breaks anything on other devices/browsers.

**Comment by marcwhitbread** [comment]
Android devices are hard to nail down because they vary in performance and quality greatly. So I added this setting as an option for processor heavy implementations or devices with weak touch responsiveness. This wont have any negative effect on other devices other than lowering the lock sensitivity and may not even be noticeable.

But if you are worried about this value effecting other devices, store the horizontalSlideLockThreshold value in a variable and do a user agent check. You could then specifically change the threshold value for certain browsers.
