### ISSUE TITLE
Hide Prev/Next Nav

### ISSUE THREAD

**Issue by synergies** [iosscripts/iosslider#56]
Ability to toggle hide for navigation controls on first (hide prev) and last (hide next) slides.

**Comment by marcwhitbread** [comment]
You could achieve this by using the onSlideChange optional parameter with something like this maybe:

``` js
$('.iosSlider').iosSlider({
    navNextSelector: $('.next'),
    navPrevSelector: $('.prev'),
    onSlideChange: slideChange
});

function slideChange(args) {

    $('.next, .prev').css({
        display: 'block'
    });

    if(args.currentSlideNumber == 0) {

        $('.prev').css({
            display: 'none'
        });

    } else if(args.currentSlideNumber == (args.numberOfSlides - 1)) {

        $('.next').css({
            display: 'none'
        });

    }

}
```

**Comment by christineramsden** [comment]
Hi I realise this issue has already been closed, so i am not sure whether I am meant to just open a new issue.  But my issue is pretty much identical to the first poster and the presented solution actually doesn't work.

The issue is when you have a few slides across a page the number that is returned as the "currentSlideNumber" is the slide to the very left of the page, so to the right of the page you may well have reached the last slide but number doesn't represent that.

Also what about when the slider first loads up and you don't want the prev arrow showing then, as this onSlideChange solution will only work after the user has moved to another slide?

Hope you can help.

Cheers
Christine

**Comment by iosscripts** [comment]
I can reopen it, no problem.

**Comment by iosscripts** [comment]
I am happy to help :)

> The issue is when you have a few slides across a page the number that is returned as the "currentSlideNumber" is the slide to the very left of the page, so to the right of the page you may well have reached the last slide but number doesn't represent that.

So your issue sounds a little different. In your case, you have multiple slides on the page at one time, correct?

> Also what about when the slider first loads up and you don't want the prev arrow showing then, as this onSlideChange solution will only work after the user has moved to another slide?

The easiest way would be to put a display: none in your css for the previous slide. That would work assuming you always start at slide 1.

**Comment by jimahyland** [comment]
Sorry to reopen this. I have the same issue as @christabella76 . I've got multiple slides on the slider, so the currentSlideNumber never gets to the last one. I guess I need to something with currentSliderOffset, maybe. What do you recommend?
