### ISSUE TITLE
Scrollbars not releasing slider control on mouseUp

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#69]
Once again video will be sent by email in a little bit.

**Comment by iosscripts** [comment]
After some research, it looks like Chrome and Safari are just ignoring all mouse events when clicking a browser scrollbar. Not sure if I will be able to override this. I will keep digging.

**Comment by iosscripts** [comment]
It's true, a bug in WebKit :(. Not fixed since '09. I have posted a reply in the bug below. Maybe if we get enough people to star it star - button about comment field - or write a comment in the bug they will take a look at it. :S

http://code.google.com/p/chromium/issues/detail?id=14204

I will close this for now and wait for an update to the bug.

**Comment by ColColonCleaner** [comment]
Commented, hope it helps! Yeah it's not a problem at all on mobile, which is my main focus right now, but we will be eventually moving it to desktop as well. Thanks for the research!
