### ISSUE TITLE
Multiple iosSliders on page

### ISSUE THREAD

**Issue by lucassena** [iosscripts/iosslider#85]
Hi,

I had to use multiple slides on a page. What do you think about this solution to select navPrevSelector and navNextSelector?

$(settings.navPrevSelector, $this.parent())

$(settings.navNextSelector, $this.parent())

**Comment by ColColonCleaner** [comment]
Looks like you are trying to write the nav selector code only once, which by the looks of it is a good approach. Where are these lines located, and what is $this in your case?

**Comment by lucassena** [comment]
Hey Cobeliga,

I changed from: $(settings.navPrevSelector) 
to: $(settings.navPrevSelector, $this.parent())

The line is about 1022 (using Version: v1.0.35).

**Comment by ColColonCleaner** [comment]
That will get the navPrevSelector in the parent element only. People may not have it in the slider's parent element. So then it would never be found.

Your code 
$(settings.navPrevSelector, $this.parent())
is the same as
$($this.parent()).find(settings.navPrevSelector)

Once again, people may not have the selectors in the slider's parent element due to their project structure.

**Comment by iosscripts** [comment]
@cobeliga is correct, the script allows you to move your selectors to be anywhere you want. In all the demos, the nav selectors just happen to be in the same hierarchy in the DOM.
